# -*- coding: utf-8 -*-
"""Level_1_House_Data_Cleaning_and_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRBn92tDWObv73Fy0vmPCbi2mYrza7Vk
"""

# @title Default title text
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

columns = [
    "CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE",
    "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV"
]

df = pd.read_csv(
    "4) house Prediction Data Set.csv",
    sep=r"\s+",
    header=None,
    names=columns
)

df.head()

df.info()

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates()

for col in df.columns:
    df[col] = df[col].fillna(df[col].median())

# Confirm final cleaned dataset shape
df.shape

# Save cleaned dataset
df.to_csv("cleaned_house_prediction_data.csv", index=False)

"""# Level 1 - Task 2: Exploratory Data Analysis

In this section, I performed exploratory data analysis on the cleaned House Prediction Dataset. The analysis includes summary statistics, data distributions, boxplots, scatter plots, and correlation analysis.
"""

df.head()

df.shape

df.info()

df.describe()

summary_stats = pd.DataFrame({
    "Mean": df.mean(),
    "Median": df.median(),
    "Mode": df.mode().iloc[0],
    "Standard Deviation": df.std()
})

summary_stats

"""The summary statistics show the central tendency and spread of each numerical feature. The dataset contains numerical housing-related variables such as crime rate, number of rooms, tax rate, pupil-teacher ratio, and house value."""

df.hist(figsize=(14, 12), bins=20)

plt.suptitle("Histograms of Numerical Features", fontsize=16)
plt.tight_layout()
plt.savefig("histograms_numerical_features.png", dpi=300, bbox_inches="tight")
plt.show()

"""The histograms show the distribution of numerical features. Some variables appear normally distributed, while others are skewed, indicating that the dataset contains unevenly distributed values."""

selected_columns = ["CRIM", "RM", "AGE", "TAX", "LSTAT", "MEDV"]

for col in selected_columns:
    plt.figure(figsize=(8, 5))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.xlabel(col)
    plt.savefig(f"boxplot_{col}.png", dpi=300, bbox_inches="tight")
    plt.show()

"""The boxplots help identify possible outliers in the dataset. Features such as CRIM and MEDV show visible outliers, which means some observations are much higher or lower than the majority of the data."""

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x="RM", y="MEDV")
plt.title("Average Number of Rooms vs House Value")
plt.xlabel("Average Number of Rooms")
plt.ylabel("House Value")
plt.savefig("scatter_rm_vs_medv.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x="LSTAT", y="MEDV")
plt.title("Lower Status Population Percentage vs House Value")
plt.xlabel("LSTAT")
plt.ylabel("House Value")
plt.savefig("scatter_lstat_vs_medv.png", dpi=300, bbox_inches="tight")
plt.show()

"""The scatter plot between RM and MEDV shows that houses with more rooms generally have higher values. The scatter plot between LSTAT and MEDV shows a negative relationship, meaning that as LSTAT increases, house value tends to decrease."""

correlation_matrix = df.corr()

correlation_matrix

plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")

plt.title("Correlation Heatmap of Numerical Features")
plt.savefig("correlation_heatmap.png", dpi=300, bbox_inches="tight")
plt.show()

"""The correlation heatmap shows relationships between numerical features. RM has a positive correlation with MEDV, meaning house value tends to increase as the average number of rooms increases. LSTAT has a negative correlation with MEDV, meaning house value tends to decrease as LSTAT increases."""

medv_correlation = df.corr()["MEDV"].sort_values(ascending=False)

medv_correlation

"""The strongest positive relationship with house value is RM. The strongest negative relationship with house value is LSTAT. This means the number of rooms and lower-status population percentage are important variables when analyzing house values.

## Task 2 Conclusion

In this exploratory data analysis, I calculated summary statistics including mean, median, mode, and standard deviation for the numerical features in the House Prediction Dataset.

I also visualized the data using histograms, boxplots, scatter plots, and a correlation heatmap. The histograms helped show feature distributions, while the boxplots helped identify possible outliers.

The scatter plots showed that RM has a positive relationship with MEDV, meaning house values tend to increase as the average number of rooms increases. LSTAT has a negative relationship with MEDV, meaning house values tend to decrease as LSTAT increases.

The correlation analysis confirmed that RM has one of the strongest positive correlations with MEDV, while LSTAT has one of the strongest negative correlations with MEDV.
"""

import zipfile
import os
from google.colab import files

# Files to include in the ZIP
files_to_zip = [
    "cleaned_house_prediction_data.csv",
    "histograms_numerical_features.png",
    "boxplot_CRIM.png",
    "boxplot_RM.png",
    "boxplot_AGE.png",
    "boxplot_TAX.png",
    "boxplot_LSTAT.png",
    "boxplot_MEDV.png",
    "scatter_rm_vs_medv.png",
    "scatter_lstat_vs_medv.png",
    "correlation_heatmap.png"
]

zip_filename = "level_1_task_1_and_2_outputs.zip"

with zipfile.ZipFile(zip_filename, "w") as zipf:
    for file in files_to_zip:
        if os.path.exists(file):
            zipf.write(file)
            print(f"Added: {file}")
        else:
            print(f"Missing: {file}")

files.download(zip_filename)

"""Downloading the files"""