# -*- coding: utf-8 -*-
"""Level_1_House_Data_Cleaning_and_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRBn92tDWObv73Fy0vmPCbi2mYrza7Vk
"""

# @title Default title text
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

columns = [
    "CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE",
    "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV"
]

df = pd.read_csv(
    "4) house Prediction Data Set.csv",
    sep=r"\s+",
    header=None,
    names=columns
)

df.head()

df.info()

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates()

for col in df.columns:
    df[col] = df[col].fillna(df[col].median())

# Confirm final cleaned dataset shape
df.shape

# Save cleaned dataset
df.to_csv("cleaned_house_prediction_data.csv", index=False)